In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "OrderID": [1, 2, 3, 4, 5],
    "Product": ["Pen", "Book", "Pen", "Bag", "Book"],
    "Category": ["Stationery", "Stationery", "Stationery", "Accessories", "Stationery"],
    "Quantity": [10, 5, 7, 2, 3],
    "Price": [10, 50, 10, 500, 50],
    "City": ["Chennai", "Madurai", "Chennai", "Trichy", "Madurai"]
}

df = pd.DataFrame(data)

df

   OrderID Product     Category  Quantity  Price     City
0        1     Pen   Stationery        10     10  Chennai
1        2    Book   Stationery         5     50  Madurai
2        3     Pen   Stationery         7     10  Chennai
3        4     Bag  Accessories         2    500   Trichy
4        5    Book   Stationery         3     50  Madurai

In [3]:
df["TotalSales"] = df["Quantity"] * df["Price"]

df

   OrderID Product     Category  Quantity  Price     City  TotalSales
0        1     Pen   Stationery        10     10  Chennai         100
1        2    Book   Stationery         5     50  Madurai         250
2        3     Pen   Stationery         7     10  Chennai          70
3        4     Bag  Accessories         2    500   Trichy        1000
4        5    Book   Stationery         3     50  Madurai         150

In [4]:
df["TotalSales"].sum()

np.int64(1570)

In [5]:
df["OrderID"].count()

np.int64(5)

In [6]:
df.groupby("Product")["TotalSales"].sum().sort_values(ascending=False)

Product
Bag     1000
Book     400
Pen      170
Name: TotalSales, dtype: int64

In [7]:
df.groupby("Category")["TotalSales"].sum()

Category
Accessories    1000
Stationery      570
Name: TotalSales, dtype: int64

In [8]:
df.groupby("City")["TotalSales"].sum()

City
Chennai     170
Madurai     400
Trichy     1000
Name: TotalSales, dtype: int64

In [9]:
df["TotalSales"].max()

1000

In [10]:
df["TotalSales"].mean()

np.float64(314.0)

In [11]:
df["Quantity"].sum()

np.int64(27)

In [12]:
df["Product"].nunique()

3

In [13]:
summary = pd.DataFrame({
    "Total Sales": [df["TotalSales"].sum()],
    "Total Orders": [df["OrderID"].count()],
    "Total Quantity": [df["Quantity"].sum()],
    "Average Order Value": [df["TotalSales"].mean()]
})

summary

   Total Sales  Total Orders  Total Quantity  Average Order Value
0         1570             5              27                314.0